DROP TABLE IF EXISTS `MENU`;
CREATE TABLE MENU(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(1000),
    PRICE INT
);

INSERT INTO MENU(NAME, PRICE)
VALUES('아메리카노',4000);

INSERT INTO MENU(NAME, PRICE)
VALUES('카페라떼',5000);

INSERT INTO MENU(NAME, PRICE)
VALUES('콜드블루',6000);

DROP TABLE IF EXISTS `NUTRITION_FACTS`;
CREATE TABLE NUTRITION_FACTS
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CALORIES        INT,
    SATURATED_FAT   INT,
    MENU_ID         INT -- 외래키
);

INSERT INTO NUTRITION_FACTS(MENU_ID, CALORIES, SATURATED_FAT)
VALUES(1, 3, 4);
INSERT INTO NUTRITION_FACTS(MENU_ID, CALORIES, SATURATED_FAT)
VALUES(2, 4, 2);
INSERT INTO NUTRITION_FACTS(MENU_ID, CALORIES, SATURATED_FAT)
VALUES(3, 2, 2);

-- DROP TABLE IF EXISTS `NUTRITION_FACTS`;
-- CREATE TABLE NUTRITION_FACTS
-- (
--     MENU_ID INT PRIMARY KEY NOT NULL,
--     CALORIES        INT,
--     SATURATED_FAT   INT
-- );

-- INSERT INTO NUTRITION_FACTS(MENU_ID, CALORIES, SATURATED_FAT)
-- VALUES(1, 3, 4);
-- INSERT INTO NUTRITION_FACTS(MENU_ID, CALORIES, SATURATED_FAT)
-- VALUES(2, 4, 2);
-- INSERT INTO NUTRITION_FACTS(MENU_ID, CALORIES, SATURATED_FAT)
-- VALUES(3, 2, 2);

DROP TABLE IF EXISTS `COMMENT`;
CREATE TABLE COMMENT
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CONTENT VARCHAR(1000),
    REGDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MENU_ID INT
);

INSERT INTO COMMENT(CONTENT, MENU_ID)
VALUES('맛있어요~!', 1);
INSERT INTO COMMENT(CONTENT, MENU_ID)
VALUES('카페라떼 짱!', 2);
INSERT INTO COMMENT(CONTENT, MENU_ID)
VALUES('커피는 아메리카노지~^^', 1);
INSERT INTO COMMENT(CONTENT, MENU_ID)
VALUES('아메리카노는 정답', 1);
INSERT INTO COMMENT(CONTENT, MENU_ID)
VALUES('여기 카페라떼는 정말 맛있어요!', 2);
INSERT INTO COMMENT(CONTENT, MENU_ID)
VALUES('아메리카노~ 좋아~ 좋아~ 좋아~~', 1);
INSERT INTO COMMENT(CONTENT, MENU_ID)
VALUES('겨울에는 역시 아이스지~!', 3);