DROP TABLE IF EXISTS `MENU`;
CREATE TABLE MENU(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(1000),
    PRICE INT
);

INSERT INTO MENU(NAME, PRICE)
VALUES('???????',4000);

INSERT INTO MENU(NAME, PRICE)
VALUES('????',5000);

INSERT INTO MENU(NAME, PRICE)
VALUES('??????',6000);

DROP TABLE IF EXISTS `NUTRITION_FACTS`;
CREATE TABLE NUTRITION_FACTS
(
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    CALORIES        INT,
    SATURATED_FAT   INT,
    MENU_ID         INT -- 외래키
);

INSERT INTO NUTRITION_FACTS(MENU_ID, CALORIES, SATURATED_FAT)
VALUES(1, 3, 4);
INSERT INTO NUTRITION_FACTS(MENU_ID, CALORIES, SATURATED_FAT)
VALUES(2, 4, 2);
INSERT INTO NUTRITION_FACTS(MENU_ID, CALORIES, SATURATED_FAT)
VALUES(3, 2, 2);

-- DROP TABLE IF EXISTS `NUTRITION_FACTS`;
-- CREATE TABLE NUTRITION_FACTS
-- (
--     MENU_ID INT PRIMARY KEY NOT NULL,
--     CALORIES        INT,
--     SATURATED_FAT   INT
-- );

-- INSERT INTO NUTRITION_FACTS(MENU_ID, CALORIES, SATURATED_FAT)
-- VALUES(1, 3, 4);
-- INSERT INTO NUTRITION_FACTS(MENU_ID, CALORIES, SATURATED_FAT)
-- VALUES(2, 4, 2);
-- INSERT INTO NUTRITION_FACTS(MENU_ID, CALORIES, SATURATED_FAT)
-- VALUES(3, 2, 2);